### ISSUE TITLE
Remove font awesome dependency 

### ISSUE THREAD

**Issue by ascott1** [cfpb/cf-expandables#15]
Since this is the only current cf- component that requires an icon (I think), would it make sense to instead serve the **+** icon as an SVG with an image fallback. That would allow us the freedom to use any icon system (cf-icons, font-awesome, custom) without effecting this plugin.

What do you think?

**Comment by himedlooff** [comment]
Actually a bunch of components require them.
- cf-buttons uses it for the [button with icon](http://cfpb.github.io/cf-buttons/docs/#button-with-icons) pattern.
- [cf-pagination](http://cfpb.github.io/cf-pagination/docs/) uses the button with icon pattern so it also need icons.
- cf-forms uses it for the [validation states](http://cfpb.github.io/cf-forms/docs/).

They all need to be updated to use cf-icons though. Is that part of your concern?

**Comment by ascott1** [comment]
Yeah, it is

**Comment by himedlooff** [comment]
Updating those components to use cf-icons should be pretty easy. While I'm fixing forms I can give it a shot.

**Comment by ascott1** [comment]
I'm more concerned with lingering browser compatibility issues.

**Comment by ascott1** [comment]
(but yes, that would be awesome)

**Comment by himedlooff** [comment]
You mean icon font browser compatibility?

**Comment by himedlooff** [comment]
For an expand/collapse I don't think it's a big deal if the icon doesn't show up in super old browsers like IE6. I mean it says _show/hide_ even if the icon font is not there right? There might be scenarios for other components though where we will have to figure out what to do when the icon fails to load and there is no accompanying text. Let me know if you start to come across that.

**Comment by ascott1** [comment]
That sounds good to me. Thanks man!

**Comment by himedlooff** [comment]
Closing this because it has been updated to cf-icons.
