### ISSUE TITLE
(+) plus icon not changing to (-) on expandables

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/cf-expandables#27]
![screen shot 2014-07-25 at 4 11 15 pm](https://cloud.githubusercontent.com/assets/3589375/3707658/e013e39c-1437-11e4-9943-8560e6955dc6.png)

**Comment by himedlooff** [comment]
Can you provide more information please? The following format should do:

```
## URL
## Actual Behavior
## Expected Behavior
## Steps to Reproduce
## Screenshot
```

**Comment by himedlooff** [comment]
Closing since there was no useful information provided.
