### ISSUE TITLE
Needs some light refactoring

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-expandables#30]
Primarily to avoid the use of double element classes.

**Comment by himedlooff** [comment]
Can you remind me what this is for?

**Comment by Scotchester** [comment]
Well, the original comment was

> Primarily to avoid the use of double element classes.

From looking at that PR, I guess I might have been referring to things like

``` html
...
<button class="expandable_header expandable_target">
    <span class="expandable_header-left expandable_label">...</span>
    <span class="expandable_header-right expandable_link">
...
```

I think it seemed odd to me to have an (HTML) element that was two separate (BEM) elements of the same block, and I just wondered if we could figure out a way around it. Definitely not a big priority, though.
