### ISSUE TITLE
Expandable cues should be hidden when no JS is available

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-expandables#40]

**Comment by Scotchester** [comment]
You mean like [this](https://github.com/cfpb/cf-component-demo/commit/0ec9b85615e7b5b761eaa86f4a677c327e1cdd7b)? :)

**Comment by himedlooff** [comment]
Yeah, that needs to be added to the docs template, currently it's only in the raw template.

**Comment by Scotchester** [comment]
Gonna have to [disagree](https://github.com/cfpb/cf-component-demo/commit/0ec9b85615e7b5b761eaa86f4a677c327e1cdd7b#diff-7) with your detective work, there, Lou.

**Comment by himedlooff** [comment]
Oh cool, sorry I was looking at the docs templates currently in use. For example cf-buttons and cf-expandables are behind the version you're pointing to and thus don't have that feature.

**Comment by KimberlyMunoz** [comment]
Hey @Scotchester, is this still an open issue?

**Comment by anselmbradford** [comment]
Reference fix in https://github.com/cfpb/cfgov-refresh/pull/1134

**Comment by KimberlyMunoz** [comment]
> Reference fix in cfpb/cfgov-refresh#1134

Hey @anselmbradford, did you mean for that to go in this issue too? https://github.com/cfpb/capital-framework/issues/236 (linking to the new one)
