### ISSUE TITLE
Better handling of missing dependencies

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cf-expandables#44]
It's not totally clear that you need to wire up `jquery.easing` in order to use this. It would be nice if the README explained this OR it would be cool if the JS would not break if `jquery.easing` wasn't available. Maybe something like:

```
if jquery.easing
    slide w/ easing
else
    just do normal linear sliding that is default to jquery
    maybe throw a useful error that says jquery.easing is missing?
```

**Comment by cfarm** [comment]
:+1: I just ran into this issue as well.

**Comment by cfarm** [comment]
ALSO CF could use better documentation of how to include JS components, period.

**Comment by KimberlyMunoz** [comment]
@sebworks @anselmbradford: Do y'all know if it's still using jquery easing?

**Comment by anselmbradford** [comment]
Yes it uses `easeOutExpo` – https://github.com/gdsmith/jquery.easing/blob/master/jquery.easing.js#L71 We could probably use [`cubic-bezier`](http://cubic-bezier.com/) in CSS instead. @jimmynotjim do you have an opinion on that? This is for the slide-down, slide-up of expandables. Possibly an issue is the current duration takes the content area height into account.

**Comment by jimmynotjim** [comment]
We could switch to using CSS using max-height, but we'd still have to do some JS to set the `max-height` and `transition-duration` inline, because you can't transition with `auto` or calculate duration in css transitions
