### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cf-expandables#5]
(Originally posted by @danny8000)

Research and test keyboard accessibilty for expandable component

**Comment by ascott1** [comment]
Not sure if something has changed from the original demo, but we make heavy use of expandables with eRegs and they are keyboard accessible. Let me know if I can be of help here!

**Comment by himedlooff** [comment]
They are currently keyboard accessible. You can tab to them and use the enter key to open and close them. Can we close this?

**Comment by himedlooff** [comment]
They have also been updated to use the button element which is better than using the anchor element. It's confusing to use an anchor element since screen reader users might wonder what "page" it links to instead of what "action" does this button do?
