### ISSUE TITLE
Click Show/Hide creates animation queue

### ISSUE THREAD

**Issue by sephcoster** [cfpb/cf-expandables#53]
I would suggest that multiple clicks on show/hide should perform only a single toggle rather than adding an animation event to the queue. Current behavior allows multiple clicks which are then executed in sequence which could be confusing to users that double-click or click multiple times.  I'll look into it.

**Comment by contolini** [comment]
I support this change!

**Comment by imuchnik** [comment]
That is a great idea @sephcoster! You are brilliant! This deserves a YOLO.

/_Jealous I haven't thought of it first ;)_/

**Comment by KimberlyMunoz** [comment]
@sebworks Did your refactoring implement this change?
