### ISSUE TITLE
Raw demo has JavaScript error

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cf-expandables#58]
https://cfpb.github.io/cf-expandables/demo/ is broken. Says `Uncaught ReferenceError: module is not defined`

**Comment by KimberlyMunoz** [comment]
Screenshot? I don't see that.

**Comment by anselmbradford** [comment]
![screen shot 2015-11-03 at 1 10 46 pm](https://cloud.githubusercontent.com/assets/704760/10916971/58ad38cc-822c-11e5-965e-0326d93d0e5d.png)
